### ISSUE TITLE
Htop

### ISSUE THREAD

**Issue by rogorido** [Relsre/dotfiles#1]
This is not an issue, but a question: how do you achieve that htop does not show any process in the screenshot on you main page?

**Comment by r3-l5-r3** [comment]
Hi there. I simply shortened the terminal window until you couldn't see it, that simple :P

**Comment by rogorido** [comment]
:) obviously... thanks, and sorry for the stupid question...

**Comment by r3-l5-r3** [comment]
You're welcome! ...and your question wasn't stupid at all. We're all just learning here :)
